name: Deploy the e-commerce/admin panel

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  check-skip-ci:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for [skip ci] in commit message
        id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[skip ci]"* ]]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

  build-and-deploy:
    needs: check-skip-ci
    if: needs.check-skip-ci.outputs.skip == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Uses Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run build

      - name: Archive generated files
        run: tar -czvf dist.tar.gz dist

      - name: Copy files via scp
        env:
          HOST: ${{ secrets.REMOTE_HOST }}
          USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no dist.tar.gz $USER@$HOST:/root/www/e-commerce/admin/
          ssh -i private_key -o StrictHostKeyChecking=no $USER@$HOST "sudo rm -rf /root/www/e-commerce/admin/dist && tar -xzvf /root/www/e-commerce/admin/dist.tar.gz -C /root/www/e-commerce/admin && sudo rm -rf /root/www/e-commerce/admin/dist.tar.gz"
          rm -rf private_key
